/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ag-ui": {
    /** Ag Ui */
    post: operations["ag_ui_ag_ui_post"];
  };
  "/agents": {
    /** Api List Agents */
    get: operations["api_list_agents_agents_get"];
  };
  "/health": {
    /** Health */
    get: operations["health_health_get"];
  };
  "/info": {
    /** Info */
    get: operations["info_info_get"];
  };
  "/models": {
    /** Api List Models */
    get: operations["api_list_models_models_get"];
  };
  "/session": {
    /** Api Session */
    get: operations["api_session_session_get"];
  };
  "/sessions/{session_id}/model": {
    /** Api Get Session Model */
    get: operations["api_get_session_model_sessions__session_id__model_get"];
    /** Api Set Session Model */
    put: operations["api_set_session_model_sessions__session_id__model_put"];
  };
  "/sessions/{session_id}/threads": {
    /** Api List Threads */
    get: operations["api_list_threads_sessions__session_id__threads_get"];
    /** Api Create Thread */
    post: operations["api_create_thread_sessions__session_id__threads_post"];
  };
  "/sessions/{session_id}/threads/{thread_id}": {
    /** Api Delete Thread */
    delete: operations["api_delete_thread_sessions__session_id__threads__thread_id__delete"];
  };
  "/sessions/{session_id}/threads/{thread_id}/agent": {
    /** Api Get Thread Agent */
    get: operations["api_get_thread_agent_sessions__session_id__threads__thread_id__agent_get"];
    /** Api Set Thread Agent */
    put: operations["api_set_thread_agent_sessions__session_id__threads__thread_id__agent_put"];
  };
  "/sessions/{session_id}/threads/{thread_id}/clear": {
    /** Api Clear Thread */
    post: operations["api_clear_thread_sessions__session_id__threads__thread_id__clear_post"];
  };
  "/sessions/{session_id}/threads/{thread_id}/events": {
    /** Api Thread Events */
    get: operations["api_thread_events_sessions__session_id__threads__thread_id__events_get"];
  };
  "/sessions/{session_id}/threads/{thread_id}/messages": {
    /** Api Thread Messages */
    get: operations["api_thread_messages_sessions__session_id__threads__thread_id__messages_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AgentInfo */
    AgentInfo: {
      /** Id */
      id: string;
      /** Name */
      name: string;
    };
    /** AgentListResponse */
    AgentListResponse: {
      /** Agents */
      agents: components["schemas"]["AgentInfo"][];
      /** Default Agent */
      default_agent: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ModelListResponse */
    ModelListResponse: {
      /** Default Model */
      default_model: string;
      /** Models */
      models: string[];
    };
    /** ServerInfoResponse */
    ServerInfoResponse: {
      /** Agent Name */
      agent_name?: string | null;
      /** Data Dir */
      data_dir: string;
      /** Pid */
      pid: number;
      /** Project Root */
      project_root: string;
      /** Version */
      version: string;
      /** Workspace Dir */
      workspace_dir: string;
      /**
       * Workspace Mode
       * @enum {string}
       */
      workspace_mode: "central" | "local";
    };
    /** SessionModelRequest */
    SessionModelRequest: {
      /** Model */
      model?: string | null;
    };
    /** SessionModelResponse */
    SessionModelResponse: {
      /** Default Model */
      default_model: string;
      /** Is Default */
      is_default: boolean;
      /** Model */
      model: string;
    };
    /** ThreadAgentRequest */
    ThreadAgentRequest: {
      /** Agent */
      agent?: string | null;
    };
    /** ThreadAgentResponse */
    ThreadAgentResponse: {
      /** Agent */
      agent: string;
      /** Agent Name */
      agent_name?: string | null;
      /** Default Agent */
      default_agent: string;
      /** Is Default */
      is_default: boolean;
    };
    /** ThreadClearResponse */
    ThreadClearResponse: {
      /** Cleared */
      cleared: string;
    };
    /** ThreadCreateRequest */
    ThreadCreateRequest: {
      /** Thread Id */
      thread_id?: string | null;
    };
    /** ThreadCreateResponse */
    ThreadCreateResponse: {
      /** Thread Id */
      thread_id: string;
    };
    /** ThreadDeleteResponse */
    ThreadDeleteResponse: {
      /** Deleted */
      deleted: string;
    };
    /** ThreadListResponse */
    ThreadListResponse: {
      /** Threads */
      threads: string[];
    };
    /** ThreadMessagesResponse */
    ThreadMessagesResponse: {
      /** Messages */
      messages: components["schemas"]["TranscriptMessage"][];
    };
    /** TranscriptMessage */
    TranscriptMessage: {
      /** Content */
      content: string;
      /**
       * Role
       * @enum {string}
       */
      role: "user" | "assistant" | "system" | "tool";
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Ag Ui */
  ag_ui_ag_ui_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Api List Agents */
  api_list_agents_agents_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AgentListResponse"];
        };
      };
    };
  };
  /** Health */
  health_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /** Info */
  info_info_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ServerInfoResponse"];
        };
      };
    };
  };
  /** Api List Models */
  api_list_models_models_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ModelListResponse"];
        };
      };
    };
  };
  /** Api Session */
  api_session_session_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /** Api Get Session Model */
  api_get_session_model_sessions__session_id__model_get: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SessionModelResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Set Session Model */
  api_set_session_model_sessions__session_id__model_put: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionModelRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SessionModelResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api List Threads */
  api_list_threads_sessions__session_id__threads_get: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Create Thread */
  api_create_thread_sessions__session_id__threads_post: {
    parameters: {
      path: {
        session_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThreadCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Delete Thread */
  api_delete_thread_sessions__session_id__threads__thread_id__delete: {
    parameters: {
      path: {
        session_id: string;
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadDeleteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Get Thread Agent */
  api_get_thread_agent_sessions__session_id__threads__thread_id__agent_get: {
    parameters: {
      path: {
        session_id: string;
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadAgentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Set Thread Agent */
  api_set_thread_agent_sessions__session_id__threads__thread_id__agent_put: {
    parameters: {
      path: {
        session_id: string;
        thread_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ThreadAgentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadAgentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Clear Thread */
  api_clear_thread_sessions__session_id__threads__thread_id__clear_post: {
    parameters: {
      path: {
        session_id: string;
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadClearResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Thread Events */
  api_thread_events_sessions__session_id__threads__thread_id__events_get: {
    parameters: {
      path: {
        session_id: string;
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Api Thread Messages */
  api_thread_messages_sessions__session_id__threads__thread_id__messages_get: {
    parameters: {
      path: {
        session_id: string;
        thread_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ThreadMessagesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
